// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/[locale]" | "/[locale]/account" | "/[locale]/account/addresses" | "/[locale]/account/addresses/[id]" | "/[locale]/account/addresses/new" | "/[locale]/account/orders" | "/[locale]/account/orders/[number]" | "/[locale]/account/profile" | "/[locale]/account/wishlist" | "/[locale]/forgot-password" | "/[locale]/legal/[key]" | "/[locale]/reset-password" | "/[locale]/shop" | "/[locale]/shop/[slug]" | "/[locale]/sign-in" | "/[locale]/sign-up" | "/admin" | "/admin/banners" | "/admin/banners/[id]" | "/admin/banners/new" | "/admin/categories" | "/admin/categories/[id]" | "/admin/categories/brands" | "/admin/categories/brands/[id]" | "/admin/categories/brands/new" | "/admin/categories/ingredients" | "/admin/categories/ingredients/[id]" | "/admin/categories/ingredients/new" | "/admin/categories/new" | "/admin/categories/tags" | "/admin/coupons" | "/admin/coupons/[code]" | "/admin/coupons/new" | "/admin/customers" | "/admin/customers/[id]" | "/admin/journal" | "/admin/journal/[id]" | "/admin/journal/new" | "/admin/media" | "/admin/orders" | "/admin/orders/[id]" | "/admin/pages" | "/admin/pages/[key]" | "/admin/pages/new" | "/admin/products" | "/admin/products/[id]" | "/admin/reviews" | "/admin/settings" | "/admin/settings/ai" | "/admin/settings/seo" | "/admin/settings/shipping" | "/admin/settings/store" | "/admin/settings/tax" | "/no-access" | "/sign-in"
type AppRouteHandlerRoutes = "/admin/customers/export" | "/admin/orders/export" | "/auth/callback" | "/auth/sign-out"
type PageRoutes = never
type LayoutRoutes = "/" | "/[locale]" | "/[locale]/account" | "/admin" | "/admin/categories" | "/admin/settings" | "/no-access" | "/sign-in"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[locale]": { "locale": string; }
  "/[locale]/account": { "locale": string; }
  "/[locale]/account/addresses": { "locale": string; }
  "/[locale]/account/addresses/[id]": { "locale": string; "id": string; }
  "/[locale]/account/addresses/new": { "locale": string; }
  "/[locale]/account/orders": { "locale": string; }
  "/[locale]/account/orders/[number]": { "locale": string; "number": string; }
  "/[locale]/account/profile": { "locale": string; }
  "/[locale]/account/wishlist": { "locale": string; }
  "/[locale]/forgot-password": { "locale": string; }
  "/[locale]/legal/[key]": { "locale": string; "key": string; }
  "/[locale]/reset-password": { "locale": string; }
  "/[locale]/shop": { "locale": string; }
  "/[locale]/shop/[slug]": { "locale": string; "slug": string; }
  "/[locale]/sign-in": { "locale": string; }
  "/[locale]/sign-up": { "locale": string; }
  "/admin": {}
  "/admin/banners": {}
  "/admin/banners/[id]": { "id": string; }
  "/admin/banners/new": {}
  "/admin/categories": {}
  "/admin/categories/[id]": { "id": string; }
  "/admin/categories/brands": {}
  "/admin/categories/brands/[id]": { "id": string; }
  "/admin/categories/brands/new": {}
  "/admin/categories/ingredients": {}
  "/admin/categories/ingredients/[id]": { "id": string; }
  "/admin/categories/ingredients/new": {}
  "/admin/categories/new": {}
  "/admin/categories/tags": {}
  "/admin/coupons": {}
  "/admin/coupons/[code]": { "code": string; }
  "/admin/coupons/new": {}
  "/admin/customers": {}
  "/admin/customers/[id]": { "id": string; }
  "/admin/customers/export": {}
  "/admin/journal": {}
  "/admin/journal/[id]": { "id": string; }
  "/admin/journal/new": {}
  "/admin/media": {}
  "/admin/orders": {}
  "/admin/orders/[id]": { "id": string; }
  "/admin/orders/export": {}
  "/admin/pages": {}
  "/admin/pages/[key]": { "key": string; }
  "/admin/pages/new": {}
  "/admin/products": {}
  "/admin/products/[id]": { "id": string; }
  "/admin/reviews": {}
  "/admin/settings": {}
  "/admin/settings/ai": {}
  "/admin/settings/seo": {}
  "/admin/settings/shipping": {}
  "/admin/settings/store": {}
  "/admin/settings/tax": {}
  "/auth/callback": {}
  "/auth/sign-out": {}
  "/no-access": {}
  "/sign-in": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/[locale]": never
  "/[locale]/account": never
  "/admin": never
  "/admin/categories": never
  "/admin/settings": never
  "/no-access": never
  "/sign-in": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
