// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/[locale]/account/addresses/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/account/addresses/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/account/addresses/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/account/addresses/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/account/addresses/new">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/account/addresses/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/account/addresses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/account/addresses">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/account/addresses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/account/orders/[number]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/account/orders/[number]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/account/orders/[number]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/account/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/account/orders">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/account/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/account">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/account/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/account/profile">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/account/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/account/wishlist/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/account/wishlist">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/account/wishlist/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/legal/[key]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/legal/[key]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/legal/[key]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/shop/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/shop/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/shop/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/shop/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/shop">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/shop/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/sign-in/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/sign-in">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/sign-in/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/sign-up/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/sign-up">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/sign-up/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/banners/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/banners/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/banners/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/banners/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/banners/new">> = Specific
  const handler = {} as typeof import("../../src/app/admin/banners/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/banners/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/banners">> = Specific
  const handler = {} as typeof import("../../src/app/admin/banners/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/categories/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/categories/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/categories/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/categories/brands/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/categories/brands/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/categories/brands/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/categories/brands/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/categories/brands/new">> = Specific
  const handler = {} as typeof import("../../src/app/admin/categories/brands/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/categories/brands/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/categories/brands">> = Specific
  const handler = {} as typeof import("../../src/app/admin/categories/brands/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/categories/ingredients/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/categories/ingredients/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/categories/ingredients/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/categories/ingredients/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/categories/ingredients/new">> = Specific
  const handler = {} as typeof import("../../src/app/admin/categories/ingredients/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/categories/ingredients/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/categories/ingredients">> = Specific
  const handler = {} as typeof import("../../src/app/admin/categories/ingredients/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/categories/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/categories/new">> = Specific
  const handler = {} as typeof import("../../src/app/admin/categories/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/categories">> = Specific
  const handler = {} as typeof import("../../src/app/admin/categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/categories/tags/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/categories/tags">> = Specific
  const handler = {} as typeof import("../../src/app/admin/categories/tags/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/coupons/[code]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/coupons/[code]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/coupons/[code]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/coupons/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/coupons/new">> = Specific
  const handler = {} as typeof import("../../src/app/admin/coupons/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/coupons/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/coupons">> = Specific
  const handler = {} as typeof import("../../src/app/admin/coupons/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/customers/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/customers/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/customers/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/customers">> = Specific
  const handler = {} as typeof import("../../src/app/admin/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/journal/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/journal/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/journal/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/journal/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/journal/new">> = Specific
  const handler = {} as typeof import("../../src/app/admin/journal/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/journal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/journal">> = Specific
  const handler = {} as typeof import("../../src/app/admin/journal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/media/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/media">> = Specific
  const handler = {} as typeof import("../../src/app/admin/media/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/orders/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/orders">> = Specific
  const handler = {} as typeof import("../../src/app/admin/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/pages/[key]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/pages/[key]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/pages/[key]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/pages/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/pages/new">> = Specific
  const handler = {} as typeof import("../../src/app/admin/pages/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/pages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/pages">> = Specific
  const handler = {} as typeof import("../../src/app/admin/pages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/products/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/products/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/products/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/products">> = Specific
  const handler = {} as typeof import("../../src/app/admin/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reviews">> = Specific
  const handler = {} as typeof import("../../src/app/admin/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/settings/ai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings/ai">> = Specific
  const handler = {} as typeof import("../../src/app/admin/settings/ai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../src/app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/settings/seo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings/seo">> = Specific
  const handler = {} as typeof import("../../src/app/admin/settings/seo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/settings/shipping/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings/shipping">> = Specific
  const handler = {} as typeof import("../../src/app/admin/settings/shipping/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/settings/store/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings/store">> = Specific
  const handler = {} as typeof import("../../src/app/admin/settings/store/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/settings/tax/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings/tax">> = Specific
  const handler = {} as typeof import("../../src/app/admin/settings/tax/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/no-access/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/no-access">> = Specific
  const handler = {} as typeof import("../../src/app/no-access/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sign-in/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-in">> = Specific
  const handler = {} as typeof import("../../src/app/sign-in/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/customers/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/admin/customers/export">> = Specific
  const handler = {} as typeof import("../../src/app/admin/customers/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/orders/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/admin/orders/export">> = Specific
  const handler = {} as typeof import("../../src/app/admin/orders/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/sign-out/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/sign-out">> = Specific
  const handler = {} as typeof import("../../src/app/auth/sign-out/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/[locale]/account/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/account">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/account/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/categories/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin/categories">> = Specific
  const handler = {} as typeof import("../../src/app/admin/categories/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/settings/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../src/app/admin/settings/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/no-access/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/no-access">> = Specific
  const handler = {} as typeof import("../../src/app/no-access/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sign-in/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/sign-in">> = Specific
  const handler = {} as typeof import("../../src/app/sign-in/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
